module.exports = {
  Bangladesh: 'bgd',
  Belgium: 'bel',
  'Burkina Faso': 'bfa',
  Bulgaria: 'bgr',
  'Bosnia and Herzegovina': 'bih',
  Barbados: 'brb',
  'Wallis and Futuna': 'wlf',
  'Saint Barthelemy': 'blm',
  Bermuda: 'bmu',
  Brunei: 'brn',
  Bolivia: 'bol',
  Bahrain: 'bhr',
  Burundi: 'bdi',
  Benin: 'ben',
  Bhutan: 'btn',
  Jamaica: 'jam',
  'Bouvet Island': 'bvt',
  Botswana: 'bwa',
  Samoa: 'wsm',
  'Bonaire, Saint Eustatius and Saba ': 'bes',
  Brazil: 'bra',
  Bahamas: 'bhs',
  Jersey: 'jey',
  Belarus: 'blr',
  Belize: 'blz',
  Russia: 'rus',
  Rwanda: 'rwa',
  Serbia: 'srb',
  'East Timor': 'tls',
  Reunion: 'reu',
  Turkmenistan: 'tkm',
  Tajikistan: 'tjk',
  Romania: 'rou',
  Tokelau: 'tkl',
  'Guinea-Bissau': 'gnb',
  Guam: 'gum',
  Guatemala: 'gtm',
  'South Georgia and the South Sandwich Islands': 'sgs',
  Greece: 'grc',
  'Equatorial Guinea': 'gnq',
  Guadeloupe: 'glp',
  Japan: 'jpn',
  Guyana: 'guy',
  Guernsey: 'ggy',
  'French Guiana': 'guf',
  Georgia: 'geo',
  Grenada: 'grd',
  'United Kingdom': 'gbr',
  Gabon: 'gab',
  'El Salvador': 'slv',
  Guinea: 'gin',
  Gambia: 'gmb',
  Greenland: 'grl',
  Gibraltar: 'gib',
  Ghana: 'gha',
  Oman: 'omn',
  Tunisia: 'tun',
  Jordan: 'jor',
  Croatia: 'hrv',
  Haiti: 'hti',
  Hungary: 'hun',
  'Hong Kong': 'hkg',
  Honduras: 'hnd',
  'Heard Island and McDonald Islands': 'hmd',
  Venezuela: 'ven',
  'Puerto Rico': 'pri',
  'Palestinian Territory': 'pse',
  Palau: 'plw',
  Portugal: 'prt',
  'Svalbard and Jan Mayen': 'sjm',
  Paraguay: 'pry',
  Iraq: 'irq',
  Panama: 'pan',
  'French Polynesia': 'pyf',
  'Papua New Guinea': 'png',
  Peru: 'per',
  Pakistan: 'pak',
  Philippines: 'phl',
  Pitcairn: 'pcn',
  Poland: 'pol',
  'Saint Pierre and Miquelon': 'spm',
  Zambia: 'zmb',
  'Western Sahara': 'esh',
  Estonia: 'est',
  Egypt: 'egy',
  'South Africa': 'zaf',
  Ecuador: 'ecu',
  Italy: 'ita',
  Vietnam: 'vnm',
  'Solomon Islands': 'slb',
  Ethiopia: 'eth',
  Somalia: 'som',
  Zimbabwe: 'zwe',
  'Saudi Arabia': 'sau',
  Spain: 'esp',
  Eritrea: 'eri',
  Montenegro: 'mne',
  Moldova: 'mda',
  Madagascar: 'mdg',
  'Saint Martin': 'maf',
  Morocco: 'mar',
  Monaco: 'mco',
  Uzbekistan: 'uzb',
  Myanmar: 'mmr',
  Mali: 'mli',
  Macao: 'mac',
  Mongolia: 'mng',
  'Marshall Islands': 'mhl',
  Macedonia: 'mkd',
  Mauritius: 'mus',
  Malta: 'mlt',
  Malawi: 'mwi',
  Maldives: 'mdv',
  Martinique: 'mtq',
  'Northern Mariana Islands': 'mnp',
  Montserrat: 'msr',
  Mauritania: 'mrt',
  'Isle of Man': 'imn',
  Uganda: 'uga',
  Tanzania: 'tza',
  Malaysia: 'mys',
  Mexico: 'mex',
  Israel: 'isr',
  France: 'fra',
  'British Indian Ocean Territory': 'iot',
  'Saint Helena': 'shn',
  Finland: 'fin',
  Fiji: 'fji',
  'Falkland Islands': 'flk',
  Micronesia: 'fsm',
  'Faroe Islands': 'fro',
  Nicaragua: 'nic',
  Netherlands: 'nld',
  Norway: 'nor',
  Namibia: 'nam',
  Vanuatu: 'vut',
  'New Caledonia': 'ncl',
  Niger: 'ner',
  'Norfolk Island': 'nfk',
  Nigeria: 'nga',
  'New Zealand': 'nzl',
  Nepal: 'npl',
  Nauru: 'nru',
  Niue: 'niu',
  'Cook Islands': 'cok',
  Kosovo: 'rks',
  'Ivory Coast': 'civ',
  Switzerland: 'che',
  Colombia: 'col',
  China: 'chn',
  Cameroon: 'cmr',
  Chile: 'chl',
  'Cocos Islands': 'cck',
  Canada: 'can',
  'Republic of the Congo': 'cog',
  'Central African Republic': 'caf',
  'Democratic Republic of the Congo': 'cod',
  'Czech Republic': 'cze',
  Cyprus: 'cyp',
  'Christmas Island': 'cxr',
  'Costa Rica': 'cri',
  Curacao: 'cuw',
  'Cape Verde': 'cpv',
  Cuba: 'cub',
  Swaziland: 'swz',
  Syria: 'syr',
  'Sint Maarten': 'sxm',
  Kyrgyzstan: 'kgz',
  Kenya: 'ken',
  'South Sudan': 'ssd',
  Suriname: 'sur',
  Kiribati: 'kir',
  Cambodia: 'khm',
  'Saint Kitts and Nevis': 'kna',
  Comoros: 'com',
  'Sao Tome and Principe': 'stp',
  Slovakia: 'svk',
  'South Korea': 'kor',
  Slovenia: 'svn',
  'North Korea': 'prk',
  Kuwait: 'kwt',
  Senegal: 'sen',
  'San Marino': 'smr',
  'Sierra Leone': 'sle',
  Seychelles: 'syc',
  Kazakhstan: 'kaz',
  'Cayman Islands': 'cym',
  Singapore: 'sgp',
  Sweden: 'swe',
  Sudan: 'sdn',
  'Dominican Republic': 'dom',
  Dominica: 'dma',
  Djibouti: 'dji',
  Denmark: 'dnk',
  'British Virgin Islands': 'vgb',
  Germany: 'deu',
  Yemen: 'yem',
  Algeria: 'dza',
  'United States': 'usa',
  Uruguay: 'ury',
  Mayotte: 'myt',
  'United States Minor Outlying Islands': 'umi',
  Lebanon: 'lbn',
  'Saint Lucia': 'lca',
  Laos: 'lao',
  Tuvalu: 'tuv',
  Taiwan: 'twn',
  'Trinidad and Tobago': 'tto',
  Turkey: 'tur',
  'Sri Lanka': 'lka',
  Liechtenstein: 'lie',
  Latvia: 'lva',
  Tonga: 'ton',
  Lithuania: 'ltu',
  Luxembourg: 'lux',
  Liberia: 'lbr',
  Lesotho: 'lso',
  Thailand: 'tha',
  'French Southern Territories': 'atf',
  Togo: 'tgo',
  Chad: 'tcd',
  'Turks and Caicos Islands': 'tca',
  Libya: 'lby',
  Vatican: 'vat',
  'Saint Vincent and the Grenadines': 'vct',
  'United Arab Emirates': 'are',
  Andorra: 'and',
  'Antigua and Barbuda': 'atg',
  Afghanistan: 'afg',
  Anguilla: 'aia',
  'U.S. Virgin Islands': 'vir',
  Iceland: 'isl',
  Iran: 'irn',
  Armenia: 'arm',
  Albania: 'alb',
  Angola: 'ago',
  Antarctica: 'ata',
  'American Samoa': 'asm',
  Argentina: 'arg',
  Australia: 'aus',
  Austria: 'aut',
  Aruba: 'abw',
  India: 'ind',
  'Aland Islands': 'ala',
  Azerbaijan: 'aze',
  Ireland: 'irl',
  Indonesia: 'idn',
  Ukraine: 'ukr',
  Qatar: 'qat',
  Mozambique: 'moz'
}
